### ISSUE TITLE
Why does seq_embed during training skip last target token

### ISSUE THREAD

**Issue by NareshGuru77** [Haiyang-W/GiT#11]
The following line in git_det_head, skips the last token (height) for input tokens:
        # input tokens for parallel training
        input_tokens = targets_tokens[:, :-1]

This leads to seq_embed skipping height during training. Is this intended? If so, could you please clarify why this is done?

Thank you!.

**Comment by nnnth** [comment]
We use autoregressive training, so the last token is not needed. The second-to-last token will predict the last token.

**Comment by NareshGuru77** [comment]
Hi. Thank you for your quick response and clarification!.
