### ISSUE TITLE
Mismatch in few-shot and zero-shot numbers between paper and code

### ISSUE THREAD

**Issue by NareshGuru77** [Haiyang-W/GiT#12]
There are discrepancies in the results of few-shot results and in one zero shot result as shown below:

![git_discrepancies](https://github.com/user-attachments/assets/f6bcb504-9d4f-423d-9de7-4b702c516986)

However, results for zero-shot cs-det, cs-seg and sun - rgbd seg match with only slight deviations.

Would it be possible that I am looking at the wrong metric or maybe there is some other issue?
Would be glad if you could help me with this. Thank you!.

**Comment by nnnth** [comment]
I think your metric is correct. We retrained the model after the paper was published, so the performance may differ from what was reported. Based on my experience, few-shot performance can vary significantly.

**Comment by NareshGuru77** [comment]
Thank you for your quick response!. So I can use the current numbers I get as the new results ?

**Comment by Haiyang-W** [comment]
yeah, I think so. :) Enjoy with the code.

**Comment by NareshGuru77** [comment]
Thank you!
