### ISSUE TITLE
AssertionError in runpy.py

### ISSUE THREAD

**Issue by dldldlfma** [Haiyang-W/GiT#2]
I try to use this awesome model like below

![image](https://github.com/Haiyang-W/GiT/assets/24381042/df93d455-ce19-472f-b4aa-6012b1005b8f)

but it's not working.

Could i ask you what is the problem?

Thank you!

**Comment by nnnth** [comment]
Your command line arguments are incorrect. The format is: 
```
bash tools/dist_test.sh configs/GiT/zero-shot/zero_shot_cityscapes_det_base.py ${ckpt_file} ${GPU_NUM} --work-dir ${work_dir}
```
where `ckpt_file` is the pre-trained model `universal_base.pth`, `GPU_NUM` indicates the number of GPUs to be used, which should be greater than or equal to 1.
