### ISSUE TITLE
torch.distributed.elastic.multiprocessing.errors.ChildFailedError in tools/train.py

### ISSUE THREAD

**Issue by zsh513** [Haiyang-W/GiT#4]
I try to train the single detection task with
"bash tools/dist_train.sh configs/GiT/single_detection_base.py  1 --work-dir output/test"

<img width="988" alt="image" src="https://github.com/Haiyang-W/GiT/assets/115225011/cd6038fe-f188-400c-ab55-7a5259456e02">
but facing the above error

Could i ask you how to solve the problem?

Thank you!

**Comment by Haiyang-W** [comment]
I suspect it might be a system or communication issue on your end, not a problem with our code here. You could try testing it on a standard server.

**Comment by zsh513** [comment]
Thank you, i debug and find that the error "SyntaxError: Failed to format the config file" in train.py line123 "runner = Runner.from_cfg(cfg)" caused the ChildFailedError, and i follow https://github.com/open-mmlab/mmdetection/issues/10974 to solve this.

**Comment by Haiyang-W** [comment]
> Thank you, i debug and find that the error "SyntaxError: Failed to format the config file" in train.py line123 "runner = Runner.from_cfg(cfg)" caused the ChildFailedError, and i follow [open-mmlab/mmdetection#10974](https://github.com/open-mmlab/mmdetection/issues/10974) to solve this.

Nice! Hope you have a good time with our codes. :)

**Comment by Haiyang-W** [comment]
For the fast training, I recommend you use 672 resolution [here](https://github.com/Haiyang-W/GiT/blob/main/configs/GiT/single_detection_base_672.py). You can also use bfloat16, will 2 times faster than fp32.

**Comment by zsh513** [comment]
Thank you very much for your project and suggestions!

**Comment by Haiyang-W** [comment]
> Thank you very much for your project and suggestions!

No problem, wish you all the best. We will also strive to integrate support for bfloat16 training as soon as possible.
