### ISSUE TITLE
Details regarding few-shot and zero shot datasets

### ISSUE THREAD

**Issue by NareshGuru77** [Haiyang-W/GiT#6]
Hi,

Thank you for the code and the Readme which are both very well organized. I am trying to setup the few-shot and zero-shot datasets. Is there any details I need to take account of?

Thank you!.

**Comment by nnnth** [comment]
Both zero-shot and few-shot datasets we use are supported by mmdetection and mmsegmentation. Please refer to the official documentation for downloading. We also provide instructions [here](https://github.com/Haiyang-W/GiT/blob/main/tools/dataset_preprocess/dataset_prepare.md).

One thing to note is that annotations for detection datasets need to be converted to COCO format. 

As for config files, we have provided details [here](https://github.com/Haiyang-W/GiT/blob/main/docs/en/customize_dataset.md).

**Comment by NareshGuru77** [comment]
Thank you for the details!. It helps a lot!

**Comment by NareshGuru77** [comment]
Hi,

Sorry for the delayed response. Some of the few shot dataset convertor scripts do not seem to be there.
tools/dataset_converters/drive.py
tools/dataset_converters/loveda.py
tools/dataset_converters/potsdam.py

Could you please provide them? 

Thank you.

**Comment by Haiyang-W** [comment]
We will check it in a few days. :) Thanks for your patience.

**Comment by nnnth** [comment]
We have updated scripts according to mmsegmentation, you can try again now.
