### ISSUE TITLE
KeyError: 'Duplicate key is not allowed among bases'

### ISSUE THREAD

**Issue by NareshGuru77** [Haiyang-W/GiT#7]
When using the large and huge few-shot configurations for loveda dataset, since the config uses both the loveda base config and the git_large config, there are overlapping keys. Issue can be resolved by creating a copy of loveda_base and replacing git_base with git_large and load_from base to large.

Is there any other way to fix this? Or am I missing something here?

Thank you!

**Comment by nnnth** [comment]
Your edits are correct. Sorry for the confusion. We'll fix this bug later.

**Comment by nnnth** [comment]
We have updated the config for few-shot. The `custom_keys` in the optimizer also need to be adjusted according to the model size. Hope everything goes well for you.

**Comment by NareshGuru77** [comment]
Hi!,
Thank you for the fixes! In the corrected configs, the custom_keys are also already adjusted? I can use them directly?

Thank you!

**Comment by nnnth** [comment]
Yes, you can use them directly. Feel free to ask if you have any other questions.
