### ISSUE TITLE
LoveDA Few Shot training annotation format

### ISSUE THREAD

**Issue by Kishaan** [Haiyang-W/GiT#8]
Hi, 

Thanks for making the code public. I'm trying to run few shot learning on LoveDA dataset. Once I start training, I get the following error.

`FileNotFoundError: [Errno 2] No such file or directory: 'data/loveDA/ann_dir/train/1040.png'`

My loveDA folder structure is as follows:

```
GiT
|──data
│   ├── loveDA
│   │   ├── img_dir
│   │   │   ├── train
│   │   │   ├── val
│   │   │   ├── test
│   │   ├── ann_dir
│   │   │   ├── train
│   │   │   |      |----- 1040.png.json
│   │   │   ├── val
```

as described here: https://github.com/Haiyang-W/GiT/blob/main/tools/dataset_preprocess/dataset_prepare.md

However, I see in the same link that I should run `python tools/dataset_converters/loveda.py /path/to/loveDA` but I don't see the file in the cloned repo. If this code is needed to fix this issue, can you please provide me with the dataset_converter file for loveda dataset?

**Comment by Haiyang-W** [comment]
We will check it in a few days. :) Thanks for your patience.  Please refer to [here](https://github.com/Haiyang-W/GiT/issues/6) later.

**Comment by nnnth** [comment]
We have updated the file according to mmsegmentation, you can try again now.

**Comment by Haiyang-W** [comment]
Thanks @nnnth . :)

**Comment by Haiyang-W** [comment]
This issue will be closed.
