### ISSUE TITLE
有没有推理的示例代码？

### ISSUE THREAD

**Issue by dream-in-night** [Haiyang-W/GiT#9]
demo 下面都是检测和分割的，没有提示词的

**Comment by dream-in-night** [comment]
demo 下面都是检测和分割的，没有提示词的

**Comment by Haiyang-W** [comment]
> demo 下面都是检测和分割的，没有提示词的

感谢你的关注。你意思是image caption？只需要给定对应的config就可以在coco caption上inference。我们没有实现通用的prompt inference。只实现了在特定数据集的evaluation。后边会考虑写一下这部分代码。感谢你的理解。
